const mongoose = require('mongoose');
const PoolSchema = new mongoose.Schema({
  timestamp: { type: String, default: Date.now() },
  id: {type: String, default: ''},
  contractId: {type: String, default: ''},
  lpToken: {
    decimals: {type: Number, default: 0},
    id: {type: String, default: ''},
    name: {type: String, default: ''},
    symbol: {type: String, default: ''},
    priceUsd: {type: String, default: ''},
  },
  lpTokenReserve: {type: String, default: ''},
  tokenA: {
    id: {type: String, default: ''},
    decimals: {type: Number, default: 0},
    icon: {type: String, default: ''},
    name: {type: String, default: ''},
    price: {type: String, default: ''},
    priceUsd: {type: String, default: ''},
    symbol: {type: String, default: ''},
    dueDiligenceComplete: {type: Boolean, default: false},
    isFeeOnTransferToken: {type: Boolean, default: false},
    description: {type: String, default: ''},
    website: {type: String, default: ''},
    sentinelReport: {type: String, default: ''},
    twitterHandle: {type: String, default: ''},
    timestampSecondsLastListingChange: {type: Number, default: 0},
  },
  tokenReserveA: {type: String, default: ''},
  tokenB: {
    id: {type: String, default: ''},
    decimals: {type: Number, default: 0},
    icon: {type: String, default: ''},
    name: {type: String, default: ''},
    price: {type: String, default: ''},
    priceUsd: {type: String, default: ''},
    symbol: {type: String, default: ''},
    dueDiligenceComplete: {type: Boolean, default: false},
    isFeeOnTransferToken: {type: Boolean, default: false},
    description: {type: String, default: ''},
    website: {type: String, default: ''},
    sentinelReport: {type: String, default: ''},
    twitterHandle: {type: String, default: ''},
    timestampSecondsLastListingChange: {type: Number, default: 0},
  },
  tokenReserveB: {type: String, default: ''},
}, { timestamps: true });

module.exports = Pool = mongoose.model('Pool', PoolSchema);
